# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibo < Formula
  desc "A CLI tool for generating .dockerignore files from templates"
  homepage "https://github.com/anton-fuji/dibo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "45c2d51b1e5ae2ca0d40c6f366691220f861e57e7c972cb0ae35027d33892075"

      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Darwin_arm64.tar.gz"
      sha256 "983cc6d3f2bc34a784ec29f5cf417deee9cf74e09b030c7892a5695f1246a256"

      def install
        bin.install "dibo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Linux_x86_64.tar.gz"
      sha256 "d06cf2dc32573d97397659337fe5a5cca61b469622748ceca4e15b6a24f4a21a"
      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Linux_arm64.tar.gz"
      sha256 "71cc23325badb5773a48b92927a544a11f5155a33b61d04c05fc32a4e0ba70f6"
      def install
        bin.install "dibo"
      end
    end
  end

  test do
    system "#{bin}/dibo", "--version"
  end
end
