# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibo < Formula
  desc "A CLI tool for generating .dockerignore files from templates"
  homepage "https://github.com/anton-fuji/dibo"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.2.0/dibo_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "ce5917dbfbd264f14c65ab5a81c2175878d0ef39b9a5b943dfc5048d63418b4c"

      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.2.0/dibo_0.2.0_Darwin_arm64.tar.gz"
      sha256 "b9d161825d90350079e99080d1155cf45144d5c0d59d6320c8af6859a826c507"

      def install
        bin.install "dibo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.2.0/dibo_0.2.0_Linux_x86_64.tar.gz"
      sha256 "2a40605b9ef28f24290da5da1edbc2c3cdb44d2e8eacdae61d195be5c06c3957"
      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.2.0/dibo_0.2.0_Linux_arm64.tar.gz"
      sha256 "4b3f8508075976d891f53ef124ac86b1737fcaf30b6863821df7ffc612dc9c85"
      def install
        bin.install "dibo"
      end
    end
  end

  test do
    system "#{bin}/dibo", "--version"
  end
end
