# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibo < Formula
  desc "A CLI tool for generating .dockerignore files from templates"
  homepage "https://github.com/anton-fuji/dibo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d44dee3d63e3edcf0392dd511fff81db97c8bdddb47e60d1a2e21b07c8fc7dc0"

      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Darwin_arm64.tar.gz"
      sha256 "6ed53208453b16c22b9bdbe16cb2634cd441245538dce6883a6a72cae31b8d45"

      def install
        bin.install "dibo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Linux_x86_64.tar.gz"
      sha256 "04e6076dd949d47fdaeb7b87bb9c4345c53ecaee94ad29e973405db4234ee2fe"
      def install
        bin.install "dibo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anton-fuji/dibo/releases/download/v0.1.0/dibo_0.1.0_Linux_arm64.tar.gz"
      sha256 "bd40f5f7ab2d3d2ae45e265dd8ebf328672b7871832ab5da015c86fb3603e8cc"
      def install
        bin.install "dibo"
      end
    end
  end

  test do
    system "#{bin}/dibo", "--version"
  end
end
